# Generated by Django 5.0.3 on 2024-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
