# Generated by Django 5.0.3 on 2024-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_opentimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opentimeslot',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
